version: "3.8"

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yml
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./loki/promtail-config.yml:/etc/promtail/config.yml
    command:
      - -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    networks:
      - monitoring

  backend:
    build:
      context: ./apps/backend
    ports:
      - "8000:8000"
    networks:
      - monitoring
    labels:
      - "app=backend"
    environment:
      - PYTHONUNBUFFERED=1  # This ensures Python logs are not buffered

  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "3000:3000"
    networks:
      - monitoring
    labels:
      - "app=frontend"

networks:
  monitoring:
    driver: bridge
