version: "3.8"

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "9100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yml
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./loki/promtail-config.yml:/etc/promtail/config.yml
    command:
      - -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "9001:3000"
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_GITHUB_ENABLED=true
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_SERVER_DOMAIN=${GF_SERVER_DOMAIN}
      - GF_AUTH_GITHUB_CLIENT_ID=${GF_AUTH_GITHUB_CLIENT_ID}
      - GF_AUTH_GITHUB_CLIENT_SECRET=${GF_AUTH_GITHUB_CLIENT_SECRET}
      - GF_AUTH_GITHUB_SCOPES=user:email,read:org
      - GF_AUTH_GITHUB_AUTH_URL=https://github.com/login/oauth/authorize
      - GF_AUTH_GITHUB_TOKEN_URL=https://github.com/login/oauth/access_token
      - GF_AUTH_GITHUB_API_URL=https://api.github.com/user
      - GF_AUTH_GITHUB_ALLOW_SIGN_UP=true
      - GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS=${GITHUB_ORGANIZATION}
      - GF_AUTH_GITHUB_ROLE_ATTRIBUTE_PATH=[login=='ps428' || login=='other_github_id'] && 'Admin' || 'Viewer'
    depends_on:
      - loki
    networks:
      - monitoring


  backend:
    build:
      context: ./apps/backend
    ports:
      - "8000:8000"
    networks:
      - monitoring
    labels:
      - "app=backend"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "3000:3000"
    networks:
      - monitoring
    labels:
      - "app=frontend"

networks:
  monitoring:
    driver: bridge