apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    version: 1
    editable: true
    isDefault: true
    jsonData:
      maxLines: 1000
      #derivedFields:
       # - datasourceUid: your_tempo_uid  # Optional: Only if you're using Tempo
        #  matcherRegex: "traceID=(\\w+)"
         # name: TraceID
          #url: "$${__value.raw}"
